### ISSUE TITLE
Typo in myQueue_TwoStacks solution

### ISSUE THREAD

**Issue by francisngo** [kuychaco/algoClass#6]
In line 123: Infinity is spelled 'Infninty'

**Comment by RebootJeff** [comment]
Great catch! Would you like to submit a PR for bonus points? 😜 
If you're not sure how, just visit [the file on Github](https://github.com/kuychaco/algoClass/blob/solutions/data-structures/queue.js), and click the pencil icon ✏️  in the upper-right. Then follow the instructions to submit a Pull Request that can be attributed to you and merged by me into the codebase.

**Comment by francisngo** [comment]
Just sent PR :)

**Comment by RebootJeff** [comment]
Closing this issue thanks to your PR 😄
